---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-h2kvm-io-v1alpha1-hyperconversion
  failurePolicy: Fail
  name: mhyperconversion.kb.io
  rules:
  - apiGroups:
    - h2kvm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hyperconversions
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-h2kvm-io-v1alpha1-hyperconversion
  failurePolicy: Fail
  name: vhyperconversion.kb.io
  rules:
  - apiGroups:
    - h2kvm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hyperconversions
  sideEffects: None
