{{- if .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperconversion-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperconversion-operator.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook-server
  selector:
    {{- include "hyperconversion-operator.selectorLabels" . | nindent 4 }}
{{- end }}
