{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hyperconversion-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperconversion-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      {{- include "hyperconversion-operator.selectorLabels" . | nindent 6 }}
{{- end }}
