# Copyright (c) 2026 ZyvorAI Labs Private Limited. All rights reserved.
# Proprietary software — see LICENSE in the repository root.
# https://zyvor.dev · info@zyvor.dev

"""Active Directory computer object cleanup for VM migrations.

Generates scripts to remove stale computer objects from Active Directory
after VM migration, preventing conflicts when the migrated VM rejoins the domain.
"""

import logging
from enum import Enum
from typing import Any, Optional

try:
    import guestfs  # type: ignore
except ImportError:
    guestfs = None  # type: ignore

logger = logging.getLogger(__name__)


class CleanupMethod(Enum):
    """Methods for AD computer object cleanup."""

    MANUAL = "manual"  # Manual cleanup instructions
    POWERSHELL_SCRIPT = "powershell"  # PowerShell script with AD cmdlets
    NETDOM = "netdom"  # Netdom command (older Windows)


def generate_cleanup_script(
    old_computer_name: str,
    domain: str,
    method: CleanupMethod = CleanupMethod.POWERSHELL_SCRIPT,
    ou_path: Optional[str] = None,
) -> str:
    """Generate Active Directory computer object cleanup script.

    Args:
        old_computer_name: Computer name to remove from AD
        domain: Domain name
        method: Cleanup method (default: PowerShell with AD cmdlets)
        ou_path: Organizational Unit path (optional)

    Returns:
        PowerShell script or manual instructions
    """
    if method == CleanupMethod.MANUAL:
        return _generate_manual_instructions(old_computer_name, domain, ou_path)
    if method == CleanupMethod.NETDOM:
        return _generate_netdom_script(old_computer_name, domain)
    return _generate_powershell_script(old_computer_name, domain, ou_path)


def stage_cleanup_script(  # pylint: disable=too-many-arguments,too-many-positional-arguments
    g: "guestfs.GuestFS",
    root: str,
    old_computer_name: str,
    domain: str,
    method: CleanupMethod = CleanupMethod.POWERSHELL_SCRIPT,
    ou_path: Optional[str] = None,
) -> dict[str, Any]:
    """Stage AD computer object cleanup script in the guest VM.

    Args:
        g: GuestFS instance
        root: Windows root path
        old_computer_name: Computer name to remove from AD
        domain: Domain name
        method: Cleanup method
        ou_path: Organizational Unit path (optional)

    Returns:
        Dict with staging results
    """
    logger.info("Staging AD cleanup script for %s", old_computer_name)

    results = {
        "success": False,
        "script_path": None,
        "method": method.value,
        "warnings": [],
    }

    try:
        script = generate_cleanup_script(old_computer_name, domain, method, ou_path)

        # Stage script
        script_dir = f"{root}/hyper2kvm/activedirectory"
        script_path = f"{script_dir}/ad-cleanup.ps1"

        g.mkdir_p(script_dir)
        g.write(script_path, script.encode("utf-8"))

        results["success"] = True
        results["script_path"] = script_path

        logger.info("AD cleanup script staged at %s", script_path)

    except Exception as e:  # pylint: disable=broad-exception-caught
        # reason: best-effort guest fixer step (guestfs I/O), must not abort the migration
        logger.exception("Failed to stage AD cleanup script: %s", e)
        logger.debug("AD cleanup staging error", exc_info=True)
        results["warnings"].append(f"Staging failed: {e}")

    return results


def _generate_powershell_script(computer_name: str, domain: str, ou_path: Optional[str]) -> str:
    """Generate PowerShell script using Active Directory cmdlets."""
    ou_filter = f"\n    -SearchBase '{ou_path}' `" if ou_path else ""

    return f"""# Active Directory Computer Object Cleanup Script
# Generated by hyper2kvm
#
# Purpose: Remove stale computer object after VM migration
# Computer: {computer_name}
# Domain: {domain}
#
# IMPORTANT: Run this script on a domain controller or a machine with
# Active Directory PowerShell module installed, using domain admin credentials.

#Requires -Modules ActiveDirectory
#Requires -RunAsAdministrator

$LogFile = "C:\\hyper2kvm\\ad-cleanup.log"
$ComputerName = "{computer_name}"
$Domain = "{domain}"

function Write-Log {{
    param($Message, $Level = "INFO")
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $LogMessage = "$Timestamp [$Level] $Message"
    $LogMessage | Out-File -Append -FilePath $LogFile

    switch ($Level) {{
        "ERROR" {{ Write-Host $LogMessage -ForegroundColor Red }}
        "WARNING" {{ Write-Host $LogMessage -ForegroundColor Yellow }}
        default {{ Write-Host $LogMessage }}
    }}
}}

Write-Log "=== Active Directory Computer Object Cleanup ==="
Write-Log "Computer: $ComputerName"
Write-Log "Domain: $Domain"

# Verify AD module is available
try {{
    Import-Module ActiveDirectory -ErrorAction Stop
    Write-Log "Active Directory module loaded successfully"
}} catch {{
    Write-Log "ERROR: Active Directory PowerShell module not found" "ERROR"
    Write-Log "Install RSAT-AD-PowerShell feature or run on domain controller" "ERROR"
    exit 1
}}

# Find computer object
Write-Log "Searching for computer object: $ComputerName"

try {{
    $Computer = Get-ADComputer -Filter {{Name -eq $ComputerName}} `
        -Server $Domain `{ou_filter}
        -ErrorAction Stop

    if ($Computer) {{
        Write-Log "Found computer object: $($Computer.DistinguishedName)"

        # Show computer details
        Write-Log "  SAM Account: $($Computer.SamAccountName)"
        Write-Log "  DNS Hostname: $($Computer.DNSHostName)"
        Write-Log "  Distinguished Name: $($Computer.DistinguishedName)"
        Write-Log "  Enabled: $($Computer.Enabled)"
        Write-Log "  Last Logon: $($Computer.LastLogonDate)"

        # Prompt for confirmation
        Write-Host ""
        Write-Host "WARNING: This will PERMANENTLY DELETE the computer object!" -ForegroundColor Yellow
        Write-Host "Computer: $($Computer.Name)" -ForegroundColor Yellow
        Write-Host "DN: $($Computer.DistinguishedName)" -ForegroundColor Yellow
        Write-Host ""

        $Confirmation = Read-Host "Type 'DELETE' to confirm deletion"

        if ($Confirmation -eq "DELETE") {{
            # Remove computer object
            try {{
                Remove-ADComputer -Identity $Computer -Server $Domain -Confirm:$false -ErrorAction Stop
                Write-Log "SUCCESS: Computer object deleted successfully" "INFO"
                Write-Log "The migrated VM can now rejoin the domain without conflicts"
                exit 0
            }} catch {{
                Write-Log "ERROR: Failed to delete computer object: $_" "ERROR"
                exit 1
            }}
        }} else {{
            Write-Log "Deletion cancelled by user" "WARNING"
            exit 2
        }}
    }} else {{
        Write-Log "Computer object not found in Active Directory" "WARNING"
        Write-Log "This is normal if the object was already removed or never existed"
        exit 0
    }}
}} catch {{
    Write-Log "ERROR: Failed to query Active Directory: $_" "ERROR"
    Write-Log "Verify domain connectivity and credentials" "ERROR"
    exit 1
}}
"""


def _generate_netdom_script(computer_name: str, domain: str) -> str:
    """Generate netdom-based cleanup script for older Windows versions."""
    # pylint: disable=duplicate-code
    # reason: the generated Write-Log PowerShell helper mirrors the one in
    # hyper2kvm/fixers/windows/performance/msi.py's
    # _generate_msi_verification_script() -- coincidental, each generated
    # script is a standalone artifact and its embedded logging helper must
    # stay intact.
    return f"""# Active Directory Computer Object Cleanup Script (Netdom)
# Generated by hyper2kvm
#
# Purpose: Remove stale computer object after VM migration
# Computer: {computer_name}
# Domain: {domain}
#
# IMPORTANT: Run this script with domain admin credentials

$LogFile = "C:\\hyper2kvm\\ad-cleanup.log"
$ComputerName = "{computer_name}"
$Domain = "{domain}"

function Write-Log {{
    param($Message)
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$Timestamp - $Message" | Out-File -Append -FilePath $LogFile
    Write-Host $Message
}}

Write-Log "=== Active Directory Computer Object Cleanup (Netdom) ==="

# Prompt for credentials
Write-Host "Enter domain administrator credentials:" -ForegroundColor Yellow
$Credential = Get-Credential -Message "Domain Admin Credentials"

if (-not $Credential) {{
    Write-Log "ERROR: Credentials required"
    exit 1
}}

$Username = $Credential.UserName
$Password = $Credential.GetNetworkCredential().Password

Write-Host ""
Write-Host "WARNING: This will remove the computer object from Active Directory!" -ForegroundColor Yellow
Write-Host "Computer: $ComputerName" -ForegroundColor Yellow
Write-Host "Domain: $Domain" -ForegroundColor Yellow
Write-Host ""

$Confirmation = Read-Host "Type 'DELETE' to confirm"

if ($Confirmation -eq "DELETE") {{
    Write-Log "Removing computer object via netdom..."

    # Use netdom to remove computer account
    $Output = netdom remove $ComputerName /domain:$Domain /userd:$Username /passwordd:$Password 2>&1

    if ($LASTEXITCODE -eq 0) {{
        Write-Log "SUCCESS: Computer object removed successfully"
        Write-Log "Output: $Output"
        exit 0
    }} else {{
        Write-Log "ERROR: Netdom command failed with exit code $LASTEXITCODE"
        Write-Log "Output: $Output"
        exit 1
    }}
}} else {{
    Write-Log "Deletion cancelled"
    exit 2
}}
"""


def _generate_manual_instructions(computer_name: str, domain: str, ou_path: Optional[str]) -> str:
    """Generate manual cleanup instructions."""
    ou_instruction = (
        f"\n3. Navigate to the Organizational Unit: {ou_path}"
        if ou_path
        else "\n3. Navigate to the appropriate Organizational Unit"
    )

    return f"""# Active Directory Computer Object Cleanup Instructions
# Generated by hyper2kvm
#
# Computer: {computer_name}
# Domain: {domain}

MANUAL CLEANUP STEPS:

1. Open Active Directory Users and Computers (dsa.msc) on a domain controller
   or administrative workstation
{ou_instruction}

4. Locate the computer object named: {computer_name}

5. Right-click the computer object and verify details:
   - Name: {computer_name}
   - Type: Computer
   - Domain: {domain}

6. Right-click the computer object and select "Delete"

7. Confirm the deletion when prompted

8. Wait for AD replication to complete (typically 15 minutes)

9. Verify deletion:
   - Run: dsquery computer -name {computer_name}
   - Should return no results

ALTERNATIVE - PowerShell Command:

On a domain controller or machine with AD PowerShell module:

    Import-Module ActiveDirectory
    Remove-ADComputer -Identity "{computer_name}" -Server "{domain}" -Confirm:$true

IMPORTANT NOTES:

- This cleanup prevents conflicts when the migrated VM rejoins the domain
- The computer object must be deleted BEFORE attempting domain rejoin
- Domain admin credentials are required
- Allow time for AD replication across all domain controllers
- If the migrated VM has a different computer name, this cleanup is optional

For automated cleanup, use the PowerShell script method instead.
"""


def get_cleanup_command(method: CleanupMethod) -> str:
    """Get the command to run the staged cleanup script.

    Args:
        method: Cleanup method used

    Returns:
        Command string to execute the script
    """
    if method == CleanupMethod.MANUAL:
        return "notepad C:\\hyper2kvm\\activedirectory\\ad-cleanup.ps1"
    return (
        "PowerShell.exe -ExecutionPolicy Bypass -NoProfile "
        "-File C:\\hyper2kvm\\activedirectory\\ad-cleanup.ps1"
    )
