# Copyright (c) 2026 ZyvorAI Labs Private Limited. All rights reserved.
# Proprietary software — see LICENSE in the repository root.
# https://zyvor.dev · info@zyvor.dev

"""Active Directory domain rejoin automation.

Generates PowerShell scripts for automated domain rejoin on first boot
after VM migration, supporting credential-based, offline, and manual methods.
"""

import json
import logging
from enum import Enum
from typing import Optional

from .extractor import DomainInfo

logger = logging.getLogger(__name__)


class DomainRejoinMethod(Enum):
    """Domain rejoin methods."""

    CREDENTIAL = "credential"  # Automated with stored credentials
    UNATTENDED = "unattended"  # Offline domain join (djoin.exe)
    MANUAL = "manual"  # Manual rejoin with instructions


# PowerShell script template for credential-based domain rejoin
# pylint: disable=duplicate-code
# reason: the generated Write-Log PowerShell helper mirrors the one in
# hyper2kvm/fixers/windows/license/reactivator.py's
# REACTIVATION_SCRIPT_TEMPLATE -- coincidental, each generated script is a
# standalone artifact and its embedded logging helper must stay intact.
CREDENTIAL_REJOIN_SCRIPT = r"""# Active Directory Domain Rejoin Script
# Generated by hyper2kvm - Automated VM Migration Toolkit

$LogFile = "C:\hyper2kvm\ad\rejoin.log"
$ConfigFile = "C:\hyper2kvm\ad\domain-info.json"
$CredentialFile = "C:\hyper2kvm\ad\credentials.xml"

function Write-Log {
    param($Message, $Level = "INFO")
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $LogLine = "$Timestamp [$Level] $Message"
    $LogLine | Out-File -Append -FilePath $LogFile -Encoding UTF8
    Write-Host $LogLine
}

Write-Log "=== Domain Rejoin Started ===" "INFO"
Write-Log "hyper2kvm AD Domain Rejoin v1.0" "INFO"

# Check if config exists
if (-not (Test-Path $ConfigFile)) {
    Write-Log "ERROR: Domain config not found at $ConfigFile" "ERROR"
    exit 1
}

try {
    $DomainInfo = Get-Content $ConfigFile -Raw | ConvertFrom-Json
    Write-Log "Loaded domain info: Domain=$($DomainInfo.Domain), Computer=$($DomainInfo.ComputerName)" "INFO"
}
catch {
    Write-Log "ERROR: Failed to parse domain config: $_" "ERROR"
    exit 1
}

# Check if credentials are available
if (-not (Test-Path $CredentialFile)) {
    Write-Log "ERROR: Domain credentials not found at $CredentialFile" "ERROR"
    Write-Log "Manual domain rejoin required - see desktop reminder" "INFO"
    exit 1
}

try {
    # Import encrypted credentials (must be run as LocalSystem)
    $Credential = Import-Clixml -Path $CredentialFile

    Write-Log "Loaded domain credentials for user: $($Credential.UserName)" "INFO"

    # Step 1: Remove from domain/workgroup first (clean break)
    Write-Log "Removing computer from current domain/workgroup..." "INFO"
    try {
        Remove-Computer -UnjoinDomainCredential $Credential -Force -Restart:$false -ErrorAction SilentlyContinue
        Write-Log "Removed from domain/workgroup" "INFO"
    }
    catch {
        Write-Log "WARNING: Could not remove from domain (may not be joined): $_" "WARN"
    }

    # Step 2: Join domain
    Write-Log "Joining domain: $($DomainInfo.Domain)" "INFO"

    $joinParams = @{
        DomainName = $DomainInfo.Domain
        Credential = $Credential
        Force = $true
        Restart = $false
        ErrorAction = "Stop"
    }

    # Add OU path if specified
    if ($DomainInfo.OUPath) {
        $joinParams['OUPath'] = $DomainInfo.OUPath
        Write-Log "Using OU path: $($DomainInfo.OUPath)" "INFO"
    }

    Add-Computer @joinParams

    Write-Log "SUCCESS: Joined domain $($DomainInfo.Domain)" "INFO"

    # Schedule reboot
    Write-Log "Scheduling reboot in 60 seconds to complete domain join..." "INFO"
    shutdown.exe /r /t 60 /c "Restarting to complete Active Directory domain join"

    # Clean up credentials for security
    Remove-Item -Path $CredentialFile -Force -ErrorAction SilentlyContinue
    Write-Log "Removed credential file for security" "INFO"

}
catch {
    Write-Log "ERROR: Failed to join domain: $_" "ERROR"
    Write-Log "Manual domain rejoin may be required" "ERROR"

    # Create desktop reminder for manual action
    $reminderPath = "C:\Users\Public\Desktop\DOMAIN-REJOIN-REQUIRED.txt"
    $reminderText = @"
IMPORTANT: Active Directory Domain Rejoin Required

This VM was migrated and needs to rejoin the domain:

Domain: $($DomainInfo.Domain)
Computer Name: $($DomainInfo.ComputerName)
OU Path: $($DomainInfo.OUPath)

Steps to manually rejoin:
1. Open System Properties (sysdm.cpl)
2. Click "Change" under Computer Name
3. Select "Domain" and enter: $($DomainInfo.Domain)
4. Provide domain administrator credentials
5. Restart when prompted

After rejoining successfully, delete this file.

Error from automatic rejoin:
$_
"@
    $reminderText | Out-File -FilePath $reminderPath -Encoding UTF8
    Write-Log "Created manual rejoin reminder at $reminderPath" "INFO"

    exit 1
}

Write-Log "=== Domain Rejoin Complete ===" "INFO"
"""

# PowerShell script template for offline domain join (djoin.exe)
UNATTENDED_REJOIN_SCRIPT = r"""# Offline Active Directory Domain Join Script
# Generated by hyper2kvm - Automated VM Migration Toolkit

$LogFile = "C:\hyper2kvm\ad\offline-join.log"
$JoinFile = "C:\hyper2kvm\ad\unattended-join.txt"

function Write-Log {
    param($Message, $Level = "INFO")
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $LogLine = "$Timestamp [$Level] $Message"
    $LogLine | Out-File -Append -FilePath $LogFile -Encoding UTF8
    Write-Host $LogLine
}

Write-Log "=== Offline Domain Join Started ===" "INFO"
Write-Log "hyper2kvm Offline Domain Join v1.0" "INFO"

# Check if offline join file exists
if (-not (Test-Path $JoinFile)) {
    Write-Log "ERROR: Offline join file not found at $JoinFile" "ERROR"
    exit 1
}

try {
    Write-Log "Executing offline domain join with djoin.exe..." "INFO"

    # Execute djoin.exe to apply offline join
    $djoinPath = "$env:SystemRoot\System32\djoin.exe"
    $arguments = @(
        "/RequestODJ",
        "/LoadFile", $JoinFile,
        "/WindowsPath", "$env:SystemRoot",
        "/LocalOS"
    )

    $process = Start-Process -FilePath $djoinPath -ArgumentList $arguments -Wait -NoNewWindow -PassThru

    if ($process.ExitCode -eq 0) {
        Write-Log "SUCCESS: Offline domain join completed" "INFO"
        Write-Log "Computer will join domain on next reboot" "INFO"

        # Schedule reboot
        Write-Log "Scheduling reboot in 60 seconds..." "INFO"
        shutdown.exe /r /t 60 /c "Restarting to complete offline domain join"

        # Clean up join file for security
        Remove-Item -Path $JoinFile -Force -ErrorAction SilentlyContinue
        Write-Log "Removed join file for security" "INFO"

    }
    else {
        Write-Log "ERROR: djoin.exe failed with exit code $($process.ExitCode)" "ERROR"
        exit 1
    }
}
catch {
    Write-Log "ERROR: Offline domain join failed: $_" "ERROR"
    exit 1
}

Write-Log "=== Offline Domain Join Complete ===" "INFO"
"""

# Manual rejoin instructions (no automation)
MANUAL_REJOIN_INSTRUCTIONS = r"""# Manual Active Directory Domain Rejoin Required
# Generated by hyper2kvm - Automated VM Migration Toolkit

========================================================================
IMPORTANT: Active Directory Domain Rejoin Required
========================================================================

This virtual machine was migrated and lost its domain membership.

Original Domain Information:
  Domain: {domain}
  Computer Name: {computer_name}
  DNS Domain: {dns_domain}
  Last DC: {last_dc}
  OU Path: {ou_path}

========================================================================
Steps to Rejoin the Domain:
========================================================================

1. Open System Properties
   - Press Win+R
   - Type: sysdm.cpl
   - Press Enter

2. Change Domain Settings
   - Click "Change" button under Computer Name tab
   - Select "Domain" radio button
   - Enter domain name: {domain}

3. Provide Credentials
   - Click OK
   - Enter domain administrator username and password
   - Username format: DOMAIN\username or user@domain.com

4. Complete Join
   - You should see "Welcome to the {domain} domain" message
   - Click OK on all dialogs
   - Restart computer when prompted

5. Verify Join
   - After restart, verify domain users can log in
   - Check network connectivity to domain controllers
   - Run: nltest /sc_query:{domain}

========================================================================
Troubleshooting:
========================================================================

If domain join fails:
- Verify DNS settings point to domain DNS servers
- Verify network connectivity to domain controller
- Check if old computer object exists in AD (may need deletion)
- Ensure computer name doesn't conflict with existing AD object
- Try manual computer object deletion: AD Users and Computers

========================================================================

After successfully rejoining the domain, delete this file.

Created by hyper2kvm v1.0
"""


# stages different script/content types depending on rejoin method (credential/unattended/manual)
def stage_domain_rejoin_script(  # pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-locals
    guestfs,
    root: str,
    domain_info: DomainInfo,
    method: DomainRejoinMethod = DomainRejoinMethod.MANUAL,
    domain_override: Optional[str] = None,
    ou_path: Optional[str] = None,
    unattended_join_file: Optional[str] = None,
) -> dict:
    """Stage domain rejoin script for first-boot execution.

    Args:
        guestfs: GuestFS instance
        root: Windows root path
        domain_info: Extracted domain information
        method: Rejoin method (credential, unattended, manual)
        domain_override: Optional domain name override
        ou_path: Optional OU path for computer object
        unattended_join_file: Path to djoin.exe output file (for unattended method)

    Returns:
        Dictionary with staging result
    """
    logger.info("Staging domain rejoin script (method: %s)", method.value)

    result = {
        "success": False,
        "method": method.value,
        "script_path": None,
        "domain_info_path": None,
        "warnings": [],
    }

    try:
        # Create AD directory
        ad_dir = f"{root}/hyper2kvm/ad"
        try:
            guestfs.mkdir_p(ad_dir)
        # best-effort mkdir; guestfs raises backend-specific exceptions for an already-existing dir
        except Exception as e:  # pylint: disable=broad-exception-caught
            logger.debug("AD directory may already exist: %s", e)

        # Use override or extracted domain
        domain = domain_override or domain_info.domain_name

        if not domain:
            logger.warning("No domain name available - cannot stage rejoin script")
            result["warnings"].append("Domain name not available")
            return result

        # Prepare domain configuration
        domain_config = {
            "Domain": domain,
            "ComputerName": domain_info.computer_name,
            "DNSDomain": domain_info.dns_domain,
            "LastDC": domain_info.last_dc,
            "OUPath": ou_path or "",
            "Method": method.value,
        }

        # Write domain info JSON
        domain_info_path = f"{ad_dir}/domain-info.json"
        domain_json = json.dumps(domain_config, indent=2)
        guestfs.write(domain_info_path, domain_json.encode("utf-8"))
        result["domain_info_path"] = domain_info_path
        logger.info("Staged domain info at %s", domain_info_path)

        # Stage appropriate script based on method
        if method == DomainRejoinMethod.CREDENTIAL:
            script_path = f"{ad_dir}/rejoin-domain.ps1"
            guestfs.write(script_path, CREDENTIAL_REJOIN_SCRIPT.encode("utf-8"))
            result["script_path"] = script_path
            logger.info("Staged credential-based rejoin script")

            result["warnings"].append(
                "Credential-based rejoin requires credentials.xml file to be staged separately"
            )

        elif method == DomainRejoinMethod.UNATTENDED:
            if not unattended_join_file:
                logger.error("Unattended join requires djoin.exe output file")
                result["warnings"].append("Unattended join file not provided")
                return result

            # Copy unattended join file
            join_file_path = f"{ad_dir}/unattended-join.txt"
            with open(unattended_join_file, "rb") as f:
                join_data = f.read()
            guestfs.write(join_file_path, join_data)
            logger.info("Staged unattended join file at %s", join_file_path)

            # Write offline join script
            script_path = f"{ad_dir}/offline-join.ps1"
            guestfs.write(script_path, UNATTENDED_REJOIN_SCRIPT.encode("utf-8"))
            result["script_path"] = script_path
            logger.info("Staged offline domain join script")

        elif method == DomainRejoinMethod.MANUAL:
            # Create desktop reminder with instructions
            reminder_path = f"{root}/Users/Public/Desktop/DOMAIN-REJOIN-REQUIRED.txt"
            instructions = MANUAL_REJOIN_INSTRUCTIONS.format(
                domain=domain,
                computer_name=domain_info.computer_name or "N/A",
                dns_domain=domain_info.dns_domain or "N/A",
                last_dc=domain_info.last_dc or "N/A",
                ou_path=ou_path or "(default Computers container)",
            )
            guestfs.write(reminder_path, instructions.encode("utf-8"))
            logger.info("Created manual rejoin reminder at %s", reminder_path)

            result["warnings"].append("Manual domain rejoin required by administrator")

        result["success"] = True
        logger.info("Domain rejoin script staged successfully")

    except Exception as e:  # pylint: disable=broad-exception-caught  # best-effort staging step, must not abort the whole migration
        logger.exception("Failed to stage domain rejoin script: %s", e)
        logger.debug("Domain rejoin staging error", exc_info=True)
        result["error"] = str(e)

    return result


def get_rejoin_command(method: DomainRejoinMethod) -> str:
    """Get the PowerShell command to execute domain rejoin script.

    Args:
        method: Rejoin method

    Returns:
        PowerShell command string for first-boot service
    """
    if method == DomainRejoinMethod.CREDENTIAL:
        return (
            r"powershell.exe -ExecutionPolicy Bypass -NoProfile "
            r"-File C:\hyper2kvm\ad\rejoin-domain.ps1"
        )
    if method == DomainRejoinMethod.UNATTENDED:
        return (
            r"powershell.exe -ExecutionPolicy Bypass -NoProfile "
            r"-File C:\hyper2kvm\ad\offline-join.ps1"
        )
    # Manual method doesn't need a command
    return ""
