# Copyright (c) 2026 ZyvorAI Labs Private Limited. All rights reserved.
# Proprietary software — see LICENSE in the repository root.
# https://zyvor.dev · info@zyvor.dev

"""Windows license reactivation automation.

Generates PowerShell scripts for automated license reactivation on first boot
after VM migration, supporting MAK, KMS, and Retail license types.
"""

import json
import logging
from typing import Optional

from .extractor import LicenseInfo, LicenseType

logger = logging.getLogger(__name__)

# PowerShell script template for license reactivation
# pylint: disable=duplicate-code
# reason: the generated Write-Log PowerShell helper mirrors the one in
# hyper2kvm/fixers/windows/activedirectory/rejoin.py's
# CREDENTIAL_REJOIN_SCRIPT/UNATTENDED_REJOIN_SCRIPT -- coincidental, each
# generated script is a standalone artifact and its embedded logging
# helper must stay intact.
REACTIVATION_SCRIPT_TEMPLATE = r"""# Windows License Reactivation Script
# Generated by hyper2kvm - Automated VM Migration Toolkit

$LogFile = "C:\hyper2kvm\license\reactivation.log"
$LicenseInfoFile = "C:\hyper2kvm\license\license-info.json"
$CredentialFile = "C:\hyper2kvm\license\credentials.xml"

function Write-Log {
    param($Message, $Level = "INFO")
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $LogLine = "$Timestamp [$Level] $Message"
    $LogLine | Out-File -Append -FilePath $LogFile -Encoding UTF8
    Write-Host $LogLine
}

Write-Log "=== Windows License Reactivation Started ===" "INFO"
Write-Log "hyper2kvm License Reactivation v1.0" "INFO"

# Check if license info exists
if (-not (Test-Path $LicenseInfoFile)) {
    Write-Log "ERROR: License info file not found at $LicenseInfoFile" "ERROR"
    exit 1
}

try {
    $LicenseInfo = Get-Content $LicenseInfoFile -Raw | ConvertFrom-Json
    Write-Log "Loaded license information: Type=$($LicenseInfo.LicenseType), Edition=$($LicenseInfo.Edition)" "INFO"
}
catch {
    Write-Log "ERROR: Failed to parse license info: $_" "ERROR"
    exit 1
}

# Reactivation based on license type
switch ($LicenseInfo.LicenseType) {
    "MAK" {
        Write-Log "Processing MAK (Multiple Activation Key) license" "INFO"

        if (-not $LicenseInfo.ProductKey) {
            Write-Log "ERROR: Product key not available for MAK license" "ERROR"
            exit 1
        }

        try {
            Write-Log "Installing product key..." "INFO"
            $output = cscript.exe //nologo C:\Windows\System32\slmgr.vbs /ipk $($LicenseInfo.ProductKey) 2>&1
            Write-Log "slmgr /ipk output: $output" "INFO"

            Write-Log "Activating Windows..." "INFO"
            $output = cscript.exe //nologo C:\Windows\System32\slmgr.vbs /ato 2>&1
            Write-Log "slmgr /ato output: $output" "INFO"

            Write-Log "SUCCESS: MAK license activated" "INFO"
        }
        catch {
            Write-Log "ERROR: MAK activation failed: $_" "ERROR"
        }
    }

    "KMS" {
        Write-Log "Processing KMS (Key Management Service) license" "INFO"

        if (-not $LicenseInfo.KMSServer) {
            Write-Log "WARNING: KMS server not specified, using DNS-based discovery" "WARN"
        }
        else {
            try {
                $kmsPort = if ($LicenseInfo.KMSPort) { $LicenseInfo.KMSPort } else { 1688 }
                $kmsHost = "$($LicenseInfo.KMSServer):$kmsPort"

                Write-Log "Configuring KMS server: $kmsHost" "INFO"
                $output = cscript.exe //nologo C:\Windows\System32\slmgr.vbs /skms $kmsHost 2>&1
                Write-Log "slmgr /skms output: $output" "INFO"
            }
            catch {
                Write-Log "ERROR: Failed to configure KMS server: $_" "ERROR"
            }
        }

        try {
            Write-Log "Activating Windows with KMS..." "INFO"
            $output = cscript.exe //nologo C:\Windows\System32\slmgr.vbs /ato 2>&1
            Write-Log "slmgr /ato output: $output" "INFO"

            Write-Log "SUCCESS: KMS license activated" "INFO"
        }
        catch {
            Write-Log "ERROR: KMS activation failed: $_" "ERROR"
        }
    }

    "Retail" {
        Write-Log "Processing Retail license" "INFO"

        if (-not $LicenseInfo.ProductKey) {
            Write-Log "ERROR: Product key not available for Retail license" "ERROR"
            exit 1
        }

        try {
            Write-Log "Installing retail product key..." "INFO"
            $output = cscript.exe //nologo C:\Windows\System32\slmgr.vbs /ipk $($LicenseInfo.ProductKey) 2>&1
            Write-Log "slmgr /ipk output: $output" "INFO"

            Write-Log "Activating Windows..." "INFO"
            $output = cscript.exe //nologo C:\Windows\System32\slmgr.vbs /ato 2>&1
            Write-Log "slmgr /ato output: $output" "INFO"

            Write-Log "SUCCESS: Retail license activated" "INFO"
        }
        catch {
            Write-Log "ERROR: Retail activation failed: $_" "ERROR"
        }
    }

    "OEM" {
        Write-Log "Detected OEM license (hardware-locked)" "WARN"
        Write-Log "OEM licenses are tied to motherboard BIOS and may require manual reactivation" "WARN"

        # Try activation anyway - might work for some OEM licenses
        try {
            Write-Log "Attempting OEM license activation..." "INFO"
            $output = cscript.exe //nologo C:\Windows\System32\slmgr.vbs /ato 2>&1
            Write-Log "slmgr /ato output: $output" "INFO"
        }
        catch {
            Write-Log "WARNING: OEM activation may require phone activation: $_" "WARN"
        }

        # Create desktop reminder
        $reminderPath = "C:\Users\Public\Desktop\WINDOWS-ACTIVATION-REQUIRED.txt"
        $reminderText = @"
IMPORTANT: Windows OEM License Activation Required

Your Windows installation has an OEM (Original Equipment Manufacturer) license
that is hardware-locked to the original motherboard BIOS.

Migration to a new virtual machine may require manual activation:

1. Open: Settings -> Update & Security -> Activation
2. Click "Change product key" if needed
3. If activation fails, click "Troubleshoot" for assistance
4. You may need to use phone activation (1-800 number)

OEM licenses may need to be replaced with Retail or Volume licenses
for virtual machine environments.

After resolving activation, delete this file.
"@
        $reminderText | Out-File -FilePath $reminderPath -Encoding UTF8
        Write-Log "Created activation reminder at $reminderPath" "INFO"
    }

    "Volume" {
        Write-Log "Processing Volume license" "INFO"

        try {
            Write-Log "Activating Volume license..." "INFO"
            $output = cscript.exe //nologo C:\Windows\System32\slmgr.vbs /ato 2>&1
            Write-Log "slmgr /ato output: $output" "INFO"

            Write-Log "SUCCESS: Volume license activated" "INFO"
        }
        catch {
            Write-Log "ERROR: Volume activation failed: $_" "ERROR"
        }
    }

    default {
        Write-Log "WARNING: Unknown license type '$($LicenseInfo.LicenseType)'" "WARN"
        Write-Log "Skipping automatic activation - manual intervention may be required" "WARN"
    }
}

# Display activation status
try {
    Write-Log "Checking final activation status..." "INFO"
    $output = cscript.exe //nologo C:\Windows\System32\slmgr.vbs /dli 2>&1
    Write-Log "License status:" "INFO"
    Write-Log "$output" "INFO"
}
catch {
    Write-Log "ERROR: Could not retrieve license status: $_" "ERROR"
}

Write-Log "=== License Reactivation Complete ===" "INFO"
"""


def stage_reactivation_script(
    guestfs,
    root: str,
    license_info: LicenseInfo,
    kms_server_override: Optional[str] = None,
    kms_port_override: Optional[int] = None,
) -> dict:
    """Stage license reactivation script for first-boot execution.

    Args:
        guestfs: GuestFS instance
        root: Windows root path
        license_info: Extracted license information
        kms_server_override: Optional KMS server override
        kms_port_override: Optional KMS port override

    Returns:
        Dictionary with staging result
    """
    logger.info("Staging Windows license reactivation script")

    result = {
        "success": False,
        "script_path": None,
        "license_info_path": None,
        "warnings": [],
    }

    try:
        # Create license directory
        license_dir = f"{root}/hyper2kvm/license"
        try:
            guestfs.mkdir_p(license_dir)
        except Exception as e:  # pylint: disable=broad-exception-caught  # best-effort mkdir, dir may already exist
            logger.debug("License directory may already exist: %s", e)

        # Apply KMS overrides if specified
        if kms_server_override:
            license_info.kms_server = kms_server_override
            logger.info("Using KMS server override: %s", kms_server_override)

        if kms_port_override:
            license_info.kms_port = kms_port_override
            logger.info("Using KMS port override: %s", kms_port_override)

        # Write license info JSON
        license_info_path = f"{license_dir}/license-info.json"
        license_json = json.dumps(license_info.to_dict(), indent=2)
        guestfs.write(license_info_path, license_json.encode("utf-8"))
        result["license_info_path"] = license_info_path
        logger.info("Staged license info at %s", license_info_path)

        # Write reactivation script
        script_path = f"{license_dir}/reactivate-license.ps1"
        guestfs.write(script_path, REACTIVATION_SCRIPT_TEMPLATE.encode("utf-8"))
        result["script_path"] = script_path
        logger.info("Staged reactivation script at %s", script_path)

        # Add warnings for specific license types
        if license_info.license_type == LicenseType.OEM:
            result["warnings"].append("OEM license detected - hardware-locked, may require phone activation")

        if license_info.license_type == LicenseType.UNKNOWN:
            result["warnings"].append("License type unknown - manual activation may be required")

        if (
            license_info.license_type == LicenseType.KMS
            and not license_info.kms_server
            and not kms_server_override
        ):
            result["warnings"].append(
                "KMS license without server configuration - will use DNS-based discovery"
            )

        result["success"] = True
        logger.info("License reactivation script staged successfully")

    except Exception as e:  # pylint: disable=broad-exception-caught  # best-effort fixer step, must not abort the whole migration
        logger.exception("Failed to stage reactivation script: %s", e)
        logger.debug("Reactivation staging error", exc_info=True)
        result["error"] = str(e)

    return result


def get_reactivation_command() -> str:
    """Get the PowerShell command to execute reactivation script.

    Returns:
        PowerShell command string for first-boot service
    """
    return (
        r"powershell.exe -ExecutionPolicy Bypass -NoProfile "
        r"-File C:\hyper2kvm\license\reactivate-license.ps1"
    )
