{{- if .Values.operator.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyper2kvm-operator.fullname" . }}
  namespace: {{ include "hyper2kvm-operator.namespace" . }}
  labels:
    {{- include "hyper2kvm-operator.operatorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.operator.metrics.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hyper2kvm-operator.operatorSelectorLabels" . | nindent 4 }}
{{- end }}
