---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hyper2kvm-worker-state
  namespace: hyper2kvm-workers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hyper2kvm-worker-events
  namespace: hyper2kvm-workers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
