apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyper2kvm-worker.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyper2kvm-worker.labels" . | nindent 4 }}
data:
  worker.conf: |
    {{ toYaml .Values.config.worker | nindent 4 }}
  daemon.yaml: |
    {{ toYaml .Values.config.daemon | nindent 4 }}
