# Copyright (c) 2026 ZyvorAI Labs Private Limited. All rights reserved.
# Proprietary software — see LICENSE in the repository root.
# https://zyvor.dev · info@zyvor.dev

"""Service layer for VMCraft internals."""

from .archive_tools import (
    dd_copy as archive_dd_copy,
    tar_in as archive_tar_in,
    tar_out as archive_tar_out,
)
from .blockdev import (
    flushbufs as blockdev_flushbufs,
    getbsz as blockdev_getbsz,
    getro as blockdev_getro,
    getsize64 as blockdev_getsize64,
    getss as blockdev_getss,
    getsz as blockdev_getsz,
    rereadpt as blockdev_rereadpt,
    setro as blockdev_setro,
    setrw as blockdev_setrw,
)
from .chroot import execute_chroot_command, execute_chroot_command_with_mounts
from .device_fs import (
    get_vfs_label,
    get_vfs_type,
    get_vfs_uuid,
    partition_to_device,
    partition_to_number,
)
from .device_lookup import (
    find_by_label,
    find_by_uuid,
    list_devices as list_attached_devices,
)
from .device_metadata import (
    blkid_lookup,
    invalidate_partition_cache,
    list_partitions_cached,
)
from .ext_attrs import (
    get_e2attrs as ext_get_e2attrs,
    set_e2attrs as ext_set_e2attrs,
)
from .filesystem_ops import call_file_ops
from .filesystem_tools import (
    btrfs_filesystem_show as fs_btrfs_filesystem_show,
    btrfs_subvolume_list as fs_btrfs_subvolume_list,
    ntfs_3g_probe as fs_ntfs_3g_probe,
    zfs_dataset_list as fs_zfs_dataset_list,
    zfs_pool_list as fs_zfs_pool_list,
)
from .inspection import (
    extract_filesystems_from_lsblk,
    get_cached_inspection_value,
    inspect_filesystems_grouped,
    inspect_get_filesystems_for_root,
    inspect_get_mountpoints,
    inspect_os,
    list_filesystems,
    parse_fstab,
)
from .lifecycle import close_backend, launch_backend, shutdown_backend
from .mounting import (
    get_mountpoints,
    get_mounts,
    mount_all_parallel,
    mount_ro,
    mount_rw,
    mount_with_fallback,
    mount_with_options,
    umount_all_and_clear_cache,
)
from .partitioning import (
    part_add as partition_add,
    part_del as partition_del,
    part_disk as partition_disk,
    part_get_parttype as partition_get_parttype,
    part_init as partition_init,
    part_set_gpt_type as partition_set_gpt_type,
    part_set_name as partition_set_name,
)
from .systemd_offline import (
    journalctl_export_to_file as offline_journalctl_export_to_file,
    journalctl_list_boots_detailed as offline_journalctl_list_boots_detailed,
    systemd_analyze_failures as offline_systemd_analyze_failures,
    systemd_analyze_plot_offline as offline_systemd_analyze_plot_offline,
    systemd_analyze_security_offline as offline_systemd_analyze_security_offline,
    systemd_analyze_time_offline as offline_systemd_analyze_time_offline,
    systemd_boot_entries as offline_systemd_boot_entries,
    systemd_boot_loader_config as offline_systemd_boot_loader_config,
    systemd_coredump_config as offline_systemd_coredump_config,
    systemd_coredump_list as offline_systemd_coredump_list,
    systemd_detect_anomalies as offline_systemd_detect_anomalies,
    systemd_detect_virt as offline_systemd_detect_virt,
    systemd_logind_config as offline_systemd_logind_config,
    systemd_machine_id as offline_systemd_machine_id,
    systemd_migration_readiness_check as offline_systemd_migration_readiness_check,
    systemd_networkd_config as offline_systemd_networkd_config,
    systemd_oomd_config as offline_systemd_oomd_config,
    systemd_portable_list as offline_systemd_portable_list,
    systemd_post_migration_validation as offline_systemd_post_migration_validation,
    systemd_pstore_list as offline_systemd_pstore_list,
    systemd_resolved_config as offline_systemd_resolved_config,
    systemd_security_compliance_check as offline_systemd_security_compliance_check,
    systemd_sysext_list as offline_systemd_sysext_list,
    systemd_sysusers_config as offline_systemd_sysusers_config,
    systemd_timesyncd_config as offline_systemd_timesyncd_config,
)
from .xfs_tools import (
    xfs_admin as fs_xfs_admin,
    xfs_db as fs_xfs_db,
    xfs_growfs as fs_xfs_growfs,
    xfs_info as fs_xfs_info,
    xfs_repair as fs_xfs_repair,
)

__all__ = [
    "archive_dd_copy",
    "archive_tar_in",
    "archive_tar_out",
    "blkid_lookup",
    "blockdev_flushbufs",
    "blockdev_getbsz",
    "blockdev_getro",
    "blockdev_getsize64",
    "blockdev_getss",
    "blockdev_getsz",
    "blockdev_rereadpt",
    "blockdev_setro",
    "blockdev_setrw",
    "call_file_ops",
    "close_backend",
    "execute_chroot_command",
    "execute_chroot_command_with_mounts",
    "ext_get_e2attrs",
    "ext_set_e2attrs",
    "extract_filesystems_from_lsblk",
    "find_by_label",
    "find_by_uuid",
    "fs_btrfs_filesystem_show",
    "fs_btrfs_subvolume_list",
    "fs_ntfs_3g_probe",
    "fs_xfs_admin",
    "fs_xfs_db",
    "fs_xfs_growfs",
    "fs_xfs_info",
    "fs_xfs_repair",
    "fs_zfs_dataset_list",
    "fs_zfs_pool_list",
    "get_cached_inspection_value",
    "get_mountpoints",
    "get_mounts",
    "get_vfs_label",
    "get_vfs_type",
    "get_vfs_uuid",
    "inspect_filesystems_grouped",
    "inspect_get_filesystems_for_root",
    "inspect_get_mountpoints",
    "inspect_os",
    "invalidate_partition_cache",
    "launch_backend",
    "list_attached_devices",
    "list_filesystems",
    "list_partitions_cached",
    "mount_all_parallel",
    "mount_ro",
    "mount_rw",
    "mount_with_fallback",
    "mount_with_options",
    "offline_journalctl_export_to_file",
    "offline_journalctl_list_boots_detailed",
    "offline_systemd_analyze_failures",
    "offline_systemd_analyze_plot_offline",
    "offline_systemd_analyze_security_offline",
    "offline_systemd_analyze_time_offline",
    "offline_systemd_boot_entries",
    "offline_systemd_boot_loader_config",
    "offline_systemd_coredump_config",
    "offline_systemd_coredump_list",
    "offline_systemd_detect_anomalies",
    "offline_systemd_detect_virt",
    "offline_systemd_logind_config",
    "offline_systemd_machine_id",
    "offline_systemd_migration_readiness_check",
    "offline_systemd_networkd_config",
    "offline_systemd_oomd_config",
    "offline_systemd_portable_list",
    "offline_systemd_post_migration_validation",
    "offline_systemd_pstore_list",
    "offline_systemd_resolved_config",
    "offline_systemd_security_compliance_check",
    "offline_systemd_sysext_list",
    "offline_systemd_sysusers_config",
    "offline_systemd_timesyncd_config",
    "parse_fstab",
    "partition_add",
    "partition_del",
    "partition_disk",
    "partition_get_parttype",
    "partition_init",
    "partition_set_gpt_type",
    "partition_set_name",
    "partition_to_device",
    "partition_to_number",
    "shutdown_backend",
    "umount_all_and_clear_cache",
]
