# PodDisruptionBudget to ensure high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hyperconversion-operator-pdb
  namespace: system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      control-plane: controller-manager
