d /run/h2kvm                              0755 root root -
d /run/h2kvm/workflow                     0755 root root -
d /run/h2kvm/workflow/to_be_processed     0755 root root -
d /run/h2kvm/workflow/processing          0755 root root -
d /run/h2kvm/workflow/processed           0755 root root -
d /run/h2kvm/workflow/failed              0755 root root -
